export const COMMENTATORS=[
  'John Motson',
  'Peter Drury',
  'José Ángel de la Casa',
  'Clive Tyldesley',
  'Andrés Cantor',
  'Brian Moore',
  'Bruno Pizzul',
  'Nicolò Carosio',
];

export const BROADCASTERS=[
  'Sky Sports',
  'Amazon Prime Video',
  'RAI',
  'BBC Sport',
  'ITV Sport',
  'ESPN',
  'Telecinco',
  'Canal+',
  'DAZN',
  'beIN Sports',
  'Mediaset',
  'Eurosport',
];

export const WEATHER_CMT={
  light_rain:'The rain is beginning to affect the surface — technical teams are finding it harder to keep possession.',
  heavy_rain:'Treacherous conditions. The technical sides are struggling, and the more physical teams are thriving in the mud.',
  storm:'Extraordinary scenes — the storm is relentless. Organisation is breaking down, and this has become a battle of pure willpower.',
  snow:'The snow keeps falling. Passes going astray, the ball bobbling — character is becoming the decisive factor tonight.',
};

export const CMT={
  goal_normal:['{A} pulls the trigger inside the area, and {T} have the breakthrough!','{A} takes one touch, then buries it with authority!','{A} was never going to miss — goal for {T}!','{A} finds the corner with ice in the veins!','{A} turns in the box, shoots low, and beats {GK}!','{A} keeps the composure and scores!','{A} with the calm of a master and the finish of a champion!','{A} side-foots it home with exquisite precision!','{A} arrives at exactly the right moment and converts!','That is proper striker stuff from {A}. One chance, one goal.','No fuss from {A}; just the finish. {T} will take that all day.','The defending is not great, but the finish from {A} is ruthless.'],
  goal_header:['{A} rises highest and powers the header home!','{A} meets the cross with a towering header!','{A} attacks the ball and thumps it past {GK}!','{A} with a magnificent leap — and a magnificent header!','{A} climbs above the defence and nods it in!','{A} towers above them all and makes it count!'],
  goal_long:['{A} from distance — oh, that is magnificent!','{A} lets fly from range and finds the top corner!','{A} unleashes an absolute rocket from outside the box!','{A} with a thunderbolt from long range!','{A} rifles it from miles out — sensational goal for {T}!','{A} detonates one from outside the area!'],
  goal_poach:['{A} is there for the simplest of finishes!','{A} taps it in from a yard out!','{A} arrives at the far post and turns it in!','{A} follows the play and pokes home the rebound!','{A} is lurking where great strikers always lurk — goal!','{A} needs only a touch, and that touch is enough!'],
  save_normal:['{GK} gets behind it and makes a comfortable save.','{GK} stands tall and deals with it well.','{GK} reads the shot early and collects with confidence.','{GK} covers the angle and frustrates {A}.','{GK} makes the stop look routine.','{GK} handles that with calm authority.','Decent hit from {A}, but {GK} is right behind it.','{A} tries to force the issue; {GK} says no, calmly.'],
  save_miracle:['{GK} with an extraordinary save to deny {A}!','{GK} has pulled off a miracle!','{GK} flies across the goal and somehow keeps it out!','{GK} claws it away from the top corner!','{GK} defies logic, gravity, and {A} with that stop!','{GK} springs to full stretch and tips it wide!','{GK} with cat-like reflexes to deny {A}!','{GK} has no right to stop that, but stops it anyway!'],
  woodwork:['{A} hammers it against the post — so close!','The ball crashes off the crossbar from {A}! Millimetres away!','{A} finds the frame of the goal but not the net — agonising!','The woodwork saves {GK}! {A} cannot believe it.','{A} clips the outside of the post!'],
  miss:['{A} snatches at it, and drags it wide.','{A} had the opening, but the finish is off target.','{A} leans back and sends it over the bar.','{A} has blazed that over, and he knows it.','{A} gets the angle wrong and misses the target.','{A} had more time than that finish suggested.','Big chance, honestly. {A} will want that one back.','That was the moment for {A}, and the stadium knows it.'],
  tackle:['{A} times that tackle to absolute perfection on {B}!','{A} gets across and strips {B} of the ball!','{A} comes flying in and wins it cleanly!','{A} judges it beautifully and halts the danger.','{A} makes a saving tackle in the nick of time!'],
  dribble:['{A} dances past one, glides past another, and keeps going!','{A} leaves {B} clutching at shadows!','{A} turns {B} inside out there.','{A} beats the defender with a shimmy and a burst!'],
  chance:['{A} finds a pocket of space, but the final ball never quite arrives.','Nice move from {T}, but it dies just as the crowd starts to rise.','{A} tries to thread it through. Good idea, not quite the execution.','There is a moment there for {T}, then it just gets crowded out.'],
  blocked:['{B} throws himself in front of {A} and blocks it. Proper defending.','{A} lines it up, but {B} reads it and takes the sting out of the shot.','Important block from {B}. That was travelling.','{B} gets a body in the way, and {T} have to start again.'],
  cross:['{A} bends one into a dangerous area, but nobody attacks it.','{A} puts it across the six-yard box. Brilliant ball, no touch.','The delivery from {A} has real pace, but it flashes through everyone.','{A} looks up and crosses early. Half a chance, nothing more.'],
  sterile:['Plenty of names on the pitch, not much rhythm right now.','The tempo drops for a spell. Lots of possession, very little bite.','This has gone a bit flat. The crowd wants more than careful passes.','A neat spell, but too neat. Someone has to take a risk.'],
  interception:['{A} reads the pass beautifully and kills the attack before it starts.','Smart positioning from {A}. That looked simple, but it mattered.','{A} steps in at exactly the right time. No drama, just class.'],
  freekick:['{A} curls it over the wall and inches wide!','{A} bends one with menace from the dead ball.','{A} catches the outside of the post with a wicked free-kick!'],
  freekick_goal:['{A} curls it perfectly around the wall — GOAL!','{A} rifles the free-kick into the top corner!','{A} bends it in with stunning precision — {T} score from the dead ball!'],
  injury:['{A} is down here, and that does not look good at all.','{A} has pulled up sharply, and the game stops around him.','{A} is receiving treatment, and the stadium has gone quiet.','{A} may have to come off here after that knock.'],
  yellow:['{A} has been booked there by the referee.','{A} picks up a yellow card — dangerous territory.','{A} sees yellow after that challenge on {B}.'],
  red:['{A} has been sent off! That is a huge moment in this match!','{A} receives a straight red — {T} will be down to ten men!'],
  sub:['{B} leaves the field; {A} takes up the task.','{A} comes on — a potentially important introduction for {T}.','{B} makes way for {A} as {T} look to change the game.'],
  ht:['That is the end of the first half, and there is plenty still simmering.','Half-time arrives with the story far from written.','The whistle goes for the interval, and this contest is beautifully poised.','The first act is complete; the second promises fireworks.','Half-time. Not perfect, not dull either — this still has a few turns left.','The managers have work to do. Plenty of talent out there, but the rhythm is still coming and going.'],
  equaliser:['Late drama! You simply could not script this.','They have found the equaliser at the death, and the stadium has lost its mind!','Just when it seemed settled, it explodes back into life!','From despair to delirium in a matter of seconds!'],
  goal_et:['{A} scores in extra time, and that could change history!','{A} digs deep and finds the goal of the night for {T}!','{A} with an extra-time strike of enormous significance!'],
  ft:['Full-time, and that is a result with real weight to it.','The final whistle goes, and the story is complete.','It is all over, and what an occasion this has been.','Full-time, and the evening will be remembered for quite some time.','That is it. Some match, that — messy in places, brilliant in others.','Full-time. Not every legend shone, but the game had a story.'],
  pen_score:['{A} steps up, strikes it, and scores!','{A} sends {GK} the wrong way from the spot!','{A} is calmness personified — the penalty is buried.','{A} drills it into the corner with complete conviction.'],
  pen_save:['{GK} saves the penalty! An enormous moment!','{GK} guesses right and keeps it out!','{GK} with a huge stop from the penalty spot!','{GK} dives full length and makes the save!'],
  momentum_a:['The momentum has shifted — {T} are sensing blood now.','A burst of energy from {T}. The crowd can sense something changing.'],
  momentum_b:['This is {T}\'s moment. The tide has turned completely.'],
};
